parameters:
#    brandbury_time_zone.example.class: Brandbury\TimeZoneBundle\Example

services:
#    brandbury_time_zone.example:
#        class: %brandbury_time_zone.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
